force-app/main/default/objects/Sensor_Event__c/Sensor_Event__c.object-meta.xml
<CustomObject>
    <label>Sensor_Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Sensor_Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensor_Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/fields/Sensor_Event__c.field-meta.xml
<CustomField>
    <fullName>Sensor_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sensor_Event</label>
    <referenceTo>Sensor_Event__c</referenceTo>
    <relationshipLabel>Sensor_Events</relationshipLabel>
    <relationshipName>Sensor_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/x__c.field-meta.xml
<CustomField>
    <fullName>x__c</fullName>
    <description>In this field You must enter x coordinate.</description>
    <inlineHelpText>Please, enter &quot;x&quot; coordinate.</inlineHelpText>
    <label>x</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/y__c.field-meta.xml
<CustomField>
    <fullName>y__c</fullName>
    <description>In this field you must enter y coordinate.</description>
    <inlineHelpText>Please enter &quot;y&quot; coordinate.</inlineHelpText>
    <label>y</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/z__c.field-meta.xml
<CustomField>
    <fullName>z__c</fullName>
    <description>In this field you must enter z coordinate</description>
    <inlineHelpText>Please, enter &quot;z&quot; coordinate</inlineHelpText>
    <label>z</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SensorRestServiceHelper.cls
public with sharing class SensorRestServiceHelper {
    public static Map<String, List<Sensor_Event__c>> getParametersFromRequest(
        RestRequest request
    ) {
        System.debug('TEST ' + request.requestBody.toString());
        Map<String, List<Sensor_Event__c>> sensorsWithEvents = new Map<String, List<Sensor_Event__c>>();
        Map<String, Object> sensorWithEvent = new Map<String, Object>();
        List<Object> params;
        try {
            params = (List<Object>) JSON.deserializeUntyped(
                request.requestBody.toString()
                    .replaceAll('[\'‘’]', '"')
                    .replaceAll('^.', '[')
                    .replaceAll('.$', ']')
            );
        } catch (Exception e) {
            throw new SensorRestService.SensorException(
                '::::INVALID INPUT::::, Please enter valid string'
            );
        }
        System.debug('params' + params);
        for (Object obj : params) {
            sensorWithEvent = (Map<String, Object>) obj;
            List<Object> listOfVectors = (List<Object>) sensorWithEvent.get(
                'vectors'
            );
            Map<String, Object> vector;
            List<Sensor_Event__c> listOfEvents = new List<Sensor_Event__c>();
            for (Object vc : listOfVectors) {
                vector = (Map<String, Object>) vc;
                Sensor_Event__c event = new Sensor_Event__c();
                event.x__c = (Integer) vector.get('x');
                event.y__c = (Integer) vector.get('y');
                event.z__c = (Integer) vector.get('z');
                listOfEvents.add(event);
            }
            sensorsWithEvents.put(
                (String) sensorWithEvent.get('sensorid'),
                listOfEvents
            );
        }
        System.debug('sensorsWithEvents' + sensorsWithEvents);
        return sensorsWithEvents;
    }
}