force-app/main/default/objects/Sensor__c/Sensor__c.object-meta.xml
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <label>Sensor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor__c/fields/Max_Vectors_Length__c.field-meta.xml
<CustomField>
    <fullName>Max_Vectors_Length__c</fullName>
    <description
  >In this field you can see the max length of all vectors related to Sensor.</description>
    <inlineHelpText
  >Read only field. Max length of all vectors related to Sensor.</inlineHelpText>
    <label>Max_Vectors_Length</label>
    <summarizedField>Sensor_Event__c.Modulus_Vector_Length__c</summarizedField>
    <summaryForeignKey>Sensor_Event__c.Sensor__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/SensorsController.cls
/** 
*
*   Class Name   : SensorsController
*   Author Email : pavel.siarzhantau@gmail.com 
*   Purpose      : primary purpose - recieve list of sensor to JS controller in appWrapper lwc.
                   SensorRestService class
*   Revisions    : 30/09/2022 - Original
*      
*
**/
public with sharing class SensorsController {
    @auraEnabled(cacheable=true)
    public static List<Sensor__c> getSensorsRecords() {
        return [
            SELECT Name, 
                   Max_Vectors_Length__c, 
                   CreatedDate, 
                   OwnerId, 
                   Owner.Name
            FROM Sensor__c
            WITH SECURITY_ENFORCED
            ORDER BY CreatedDate DESC
        ];
    }
}