force-app/main/default/objects/Sensor__c/Sensor__c.object-meta.xml
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <label>Sensor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/Sensor_Event__c.object-meta.xml
<CustomObject>
    <label>Sensor_Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Sensor_Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensor_Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/fields/Sensor__c.field-meta.xml
<CustomField>
    <fullName>Sensor__c</fullName>
    <description
  >In this field you must enter particular Sensor from list.</description>
    <inlineHelpText>Please enter sensor.</inlineHelpText>
    <label>Sensor</label>
    <referenceTo>Sensor__c</referenceTo>
    <relationshipLabel>Sensor_Events</relationshipLabel>
    <relationshipName>Sensor_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/Sensor_Event__c.field-meta.xml
<CustomField>
    <fullName>Sensor_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sensor_Event</label>
    <referenceTo>Sensor_Event__c</referenceTo>
    <relationshipLabel>Sensor_Events</relationshipLabel>
    <relationshipName>Sensor_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SensorRestService.cls
@RestResource(urlMapping='/Sensors/*')
global with sharing class SensorRestService {
    global with sharing class SensorWrapper {
        global SensorWrapper() {
            System.debug('init constructor');
        }
        global SensorWrapper(Boolean isError, String message) {
            this.createdAndUpdatedSensors = new List<Sensor__c>();
            if (isError) {
                this.statusCode = 500;
                this.isError = true;
                this.errorMessage = message;
            } else {
                this.statusCode = 200;
                this.isError = false;
                this.errorMessage = '::::NO ERROR::::';
            }
        }
        global List<Sensor__c> createdAndUpdatedSensors { get; set; }
        global Boolean isError { get; set; }
        global String errorMessage { get; set; }
        global Integer statusCode { get; set; }
    }
    global class SensorException extends Exception {
    }
    @HttpPost
    global static SensorRestService.SensorWrapper createOrUpdateSensorWithEvents() {
        Map<String, List<Sensor_Event__c>> sensorsWithEvents = new Map<String, List<Sensor_Event__c>>();
        Set<String> sensorNamesFromRequest = new Set<String>();
        List<Sensor__c> duplicateSensors = new List<Sensor__c>();
        Map<String, Sensor__c> duplicateSensorsMap = new Map<String, Sensor__c>();
        Map<String, List<SObject>> separetedSensors = new Map<String, List<SObject>>();
        //CREATE sensors and events
        try {
            sensorsWithEvents = SensorRestServiceHelper.getParametersFromRequest(
                RestContext.request
            );
        } catch (SensorException e) {
            return new SensorRestService.SensorWrapper(true, e.getMessage());
        }
        sensorNamesFromRequest = sensorsWithEvents.keySet();
        duplicateSensors = SensorRestServiceModel.getduplicateSensors(
            sensorNamesFromRequest
        );
        duplicateSensorsMap = SensorRestServiceHelper.getduplicateSensorsMap(
            duplicateSensors
        );
        separetedSensors = SensorRestServiceHelper.separateSensors(
            duplicateSensorsMap,
            sensorsWithEvents
        );
        SensorRestService.SensorWrapper response = new SensorRestService.SensorWrapper(
            false,
            '::::NO ERROR::::'
        );
        response.createdAndUpdatedSensors = sensorsToUpdate;
        return response;
    }
}