force-app/main/default/objects/Sensor__c/Sensor__c.object-meta.xml
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <label>Sensor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/Sensor_Event__c.object-meta.xml
<CustomObject>
    <label>Sensor_Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Sensor_Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensor_Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/fields/Sensor__c.field-meta.xml
<CustomField>
    <fullName>Sensor__c</fullName>
    <description
  >In this field you must enter particular Sensor from list.</description>
    <inlineHelpText>Please enter sensor.</inlineHelpText>
    <label>Sensor</label>
    <referenceTo>Sensor__c</referenceTo>
    <relationshipLabel>Sensor_Events</relationshipLabel>
    <relationshipName>Sensor_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/Sensor_Event__c.field-meta.xml
<CustomField>
    <fullName>Sensor_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sensor_Event</label>
    <referenceTo>Sensor_Event__c</referenceTo>
    <relationshipLabel>Sensor_Events</relationshipLabel>
    <relationshipName>Sensor_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SensorRestServiceTest.cls
@isTest
public with sharing class SensorRestServiceTest {
    @isTest
    static void testCreateOrUpdateSensorSensorPositiveInput() {
        User user = TestDataFactory.createTestUser('Integration Profile');
        RestRequest request = TestDataFactory.createMockRequest(true);
        RestContext.request = request;
        String message = '::::NO ERROR::::';
        Integer statusCode = 200;
        Boolean isError = false;
        SensorRestService.SensorWrapper requestToUser = new SensorRestService.SensorWrapper();
        List<Sensor__c> listOfSensors = new List<Sensor__c>();
        System.runAs(user) {
            Test.startTest();
            requestToUser = SensorRestService.createOrUpdateSensorWithEvents();
            Test.stopTest();
        }
        System.debug('request:::: ' + requestToUser);
        listOfSensors = [
            SELECT Id, Name, (SELECT Id, Name FROM Sensor_Events__r)
            FROM Sensor__c
        ];
        System.assertEquals(
            listOfSensors.size(),
            requestToUser.createdAndUpdatedSensors.size(),
            'Test: createSensorPositive() is failed'
        );
        System.assertEquals(
            message,
            requestToUser.errorMessage,
            'Test: createSensorPositive() is failed'
        );
        System.assertEquals(
            statusCode,
            requestToUser.statusCode,
            'Test: createSensorPositive() is failed'
        );
        System.assertEquals(
            isError,
            requestToUser.isError,
            'Test: createSensorPositive() is failed'
        );
    }
    @isTest
    static void testCreateOrUpdateSensorrNegativeWrongInput() {
        User user = TestDataFactory.createTestUser('Integration Profile');
        RestRequest request = TestDataFactory.createMockRequest(false);
        RestContext.request = request;
        String message = '::::INVALID INPUT::::, Please enter valid string';
        Integer statusCode = 500;
        Boolean isError = true;
        SensorRestService.SensorWrapper requestToUser = new SensorRestService.SensorWrapper();
        List<Sensor__c> listOfSensors = new List<Sensor__c>();
        System.runAs(user) {
            Test.startTest();
            requestToUser = SensorRestService.createOrUpdateSensorWithEvents();
            Test.stopTest();
        }
        System.debug('request:::: ' + requestToUser);
        listOfSensors = [
            SELECT Id, Name, (SELECT Id, Name FROM Sensor_Events__r)
            FROM Sensor__c
        ];
        System.AssertEquals(
            listOfSensors.size(),
            requestToUser.createdAndUpdatedSensors.size(),
            'Test: createSensorPositive() is failed'
        );
        System.assertEquals(
            message,
            requestToUser.errorMessage,
            'Test: createSensorPositive() is failed'
        );
        System.assertEquals(
            statusCode,
            requestToUser.statusCode,
            'Test: createSensorPositive() is failed'
        );
        System.assertEquals(
            isError,
            requestToUser.isError,
            'Test: createSensorPositive() is failed'
        );
    }
}