force-app/main/default/objects/Sensor__c/Sensor__c.object-meta.xml
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <label>Sensor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/Sensor_Event__c.object-meta.xml
<CustomObject>
    <label>Sensor_Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Sensor_Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensor_Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/fields/Sensor__c.field-meta.xml
<CustomField>
    <fullName>Sensor__c</fullName>
    <description
  >In this field you must enter particular Sensor from list.</description>
    <inlineHelpText>Please enter sensor.</inlineHelpText>
    <label>Sensor</label>
    <referenceTo>Sensor__c</referenceTo>
    <relationshipLabel>Sensor_Events</relationshipLabel>
    <relationshipName>Sensor_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/Sensor_Event__c.field-meta.xml
<CustomField>
    <fullName>Sensor_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sensor_Event</label>
    <referenceTo>Sensor_Event__c</referenceTo>
    <relationshipLabel>Sensor_Events</relationshipLabel>
    <relationshipName>Sensor_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SensorRestServiceModel.cls
public with sharing class SensorRestServiceModel {
    public static List<Sensor__c> getduplicateSensors(Set<String> sensorNamesFromRequest) {
        return [
            SELECT Id, 
                   Name, 
                   (SELECT Id, 
                           Name 
                    FROM Sensor_Events__r 
                    ORDER BY Name 
                    DESC LIMIT 1)
            FROM Sensor__c
            WHERE Name IN :sensorNamesFromRequest
            WITH SECURITY_ENFORCED
        ];
    }
    public static List<Sensor__c> getSensorsToUpdate(
        List<Sensor_Event__c> sensorEventsToCrearte,
        Set<String> sensorNamesFromRequest
    ) {
        return [
            SELECT Id,
                   Name,
                   (SELECT Id, 
                           Name, 
                           Sensor_Event__c, 
                           Sensor__r.Name
                    FROM Sensor_Events__r
                    WHERE Id IN :sensorEventsToCrearte
                    ORDER BY Name ASC
                )
            FROM Sensor__c
            WHERE Name IN :sensorNamesFromRequest
            WITH SECURITY_ENFORCED
        ];
    }
}