force-app/main/default/objects/Sensor__c/Sensor__c.object-meta.xml
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <label>Sensor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor__c/fields/Max_Vectors_Length__c.field-meta.xml
<CustomField>
    <fullName>Max_Vectors_Length__c</fullName>
    <description
  >In this field you can see the max length of all vectors related to Sensor.</description>
    <inlineHelpText
  >Read only field. Max length of all vectors related to Sensor.</inlineHelpText>
    <label>Max_Vectors_Length</label>
    <summarizedField>Sensor_Event__c.Modulus_Vector_Length__c</summarizedField>
    <summaryForeignKey>Sensor_Event__c.Sensor__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/Sensor_Event__c.object-meta.xml
<CustomObject>
    <label>Sensor_Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Sensor_Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensor_Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/fields/Modulus_Vector_Length__c.field-meta.xml
<CustomField>
    <fullName>Modulus_Vector_Length__c</fullName>
    <description
  >This field shows result: Modulus_Vector_Length (√x2 + y2 + z 2)</description>
    <formula>SQRT( x__c  ^  2 +  y__c  ^  2 +  z__c  ^  2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText
  >Read only field, you can&apos;t edit this field.</inlineHelpText>
    <label>Modulus_Vector_Length</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/Sensor__c.field-meta.xml
<CustomField>
    <fullName>Sensor__c</fullName>
    <description
  >In this field you must enter particular Sensor from list.</description>
    <inlineHelpText>Please enter sensor.</inlineHelpText>
    <label>Sensor</label>
    <referenceTo>Sensor__c</referenceTo>
    <relationshipLabel>Sensor_Events</relationshipLabel>
    <relationshipName>Sensor_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/Sensor_Event__c.field-meta.xml
<CustomField>
    <fullName>Sensor_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sensor_Event</label>
    <referenceTo>Sensor_Event__c</referenceTo>
    <relationshipLabel>Sensor_Events</relationshipLabel>
    <relationshipName>Sensor_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/x__c.field-meta.xml
<CustomField>
    <fullName>x__c</fullName>
    <description>In this field You must enter x coordinate.</description>
    <inlineHelpText>Please, enter &quot;x&quot; coordinate.</inlineHelpText>
    <label>x</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/y__c.field-meta.xml
<CustomField>
    <fullName>y__c</fullName>
    <description>In this field you must enter y coordinate.</description>
    <inlineHelpText>Please enter &quot;y&quot; coordinate.</inlineHelpText>
    <label>y</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/z__c.field-meta.xml
<CustomField>
    <fullName>z__c</fullName>
    <description>In this field you must enter z coordinate</description>
    <inlineHelpText>Please, enter &quot;z&quot; coordinate</inlineHelpText>
    <label>z</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SensorEvenstController.cls
public with sharing class SensorEvenstController {
    @auraEnabled(cacheable=true)
    public static List<Sensor_Event__c> getSensorsEventsRecords(
        String recordId
    ) {
        return [
            SELECT
                Name,
                Modulus_Vector_Length__c,
                x__c,
                y__c,
                z__c,
                Sensor__r.Max_Vectors_Length__c,
                Sensor_Event__r.Name,
                Sensor__r.Name,
                CreatedDate
            FROM Sensor_Event__c
            WHERE Sensor__c = :recordId
            WITH SECURITY_ENFORCED
            ORDER BY Name DESC
        ];
    }
}