force-app/main/default/objects/Sensor__c/Sensor__c.object-meta.xml
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <label>Sensor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/Sensor_Event__c.object-meta.xml
<CustomObject>
    <label>Sensor_Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Sensor_Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensor_Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/fields/Sensor__c.field-meta.xml
<CustomField>
    <fullName>Sensor__c</fullName>
    <description
  >In this field you must enter particular Sensor from list.</description>
    <inlineHelpText>Please enter sensor.</inlineHelpText>
    <label>Sensor</label>
    <referenceTo>Sensor__c</referenceTo>
    <relationshipLabel>Sensor_Events</relationshipLabel>
    <relationshipName>Sensor_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/Sensor_Event__c.field-meta.xml
<CustomField>
    <fullName>Sensor_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sensor_Event</label>
    <referenceTo>Sensor_Event__c</referenceTo>
    <relationshipLabel>Sensor_Events</relationshipLabel>
    <relationshipName>Sensor_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sensor_Tracking_Event__e/Sensor_Tracking_Event__e.object-meta.xml
<CustomObject>
    <label>Sensor Tracking Event</label>
    <pluralLabel>Sensors Tracking Event</pluralLabel>
</CustomObject>

force-app/main/default/objects/Sensor_Tracking_Event__e/fields/message__c.field-meta.xml
<CustomField>
    <fullName>message__c</fullName>
    <label>message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sensor_Tracking_Event__e/fields/Sensors_names__c.field-meta.xml
<CustomField>
    <fullName>Sensors_names__c</fullName>
    <label>Sensors names</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SensorPlatformEventHelper.cls
public with sharing class SensorPlatformEventHelper {
    public class SensorPaltformEventException extends Exception {
    }
    @TestVisible
    public static Boolean isTest = false;
    public static Boolean isInsert = false;
    public static List<Sensor_Tracking_Event__e> events = new List<Sensor_Tracking_Event__e>();
    public static final String TEST_EXCEPTION_MESSAGE = 'Test Error';
    //Publish event after insert, after update, after delete on Sensor__c and Sensor_Event__c object
    public static void publishEvent(List<SObject> sensorList, String context) {
        Sensor_Tracking_Event__e event = new Sensor_Tracking_Event__e();
        List<String> namesOfSensors = new List<String>();
        String objectName = sensorList[0]
            .getSObjectType()
            .getDescribe()
            .getLabel();
        for (SObject sensor : sensorList) {
            if (sensor.getSObjectType() == Sensor__c.getSObjectType()) {
                Sensor__c sen = (Sensor__c) sensor;
                namesOfSensors.add(objectName + ': ' + sen.Name + '\n');
            } else if (
                sensor.getSObjectType() == Sensor_Event__c.getSObjectType()
            ) {
                Sensor_Event__c evt = (Sensor_Event__c) sensor;
                namesOfSensors.add(objectName + ': ' + evt.Name + '\n');
            }
        }
        event.Sensors_names__c = String.join(namesOfSensors, '');
        switch on context {
            when 'BEFORE_INSERT' {
                isInsert = true;
                System.debug('isInsert::: ' + isInsert);
            }
            when 'AFTER_INSERT' {
                event.message__c = objectName + '(s) were inserted.';
                events.add(event);
                sendEventToEventBus(event);
                System.debug(objectName + '(s) was inserted');
            }
            when 'AFTER_UPDATE' {
                if (!isInsert) {
                    event.message__c = objectName + '(s) were updated.';
                    events.add(event);
                    sendEventToEventBus(event);
                    System.debug(objectName + '(s) were updated');
                }
            }
            when 'AFTER_DELETE' {
                event.message__c = objectName + '(s) were deleted.';
                events.add(event);
                sendEventToEventBus(event);
                System.debug(objectName + '(s) were deleted');
            }
        }
    }
    @TestVisible
    private static void sendEventToEventBus(Sensor_Tracking_Event__e event) {
        try {
            if (isTest && Test.isRunningTest()) {
                throw new SensorPaltformEventException(TEST_EXCEPTION_MESSAGE);
            }
            EventBus.publish(event);
        } catch (Exception e) {
            throw new SensorPaltformEventException(
                'Some error occured, when publishing event: ' + e.getMessage()
            );
        }
    }
}